config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'authors/index'
  get 'authors/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/edit'
  get 'authors/update'
  get 'authors/destroy'
  resources :orders
  # resources :paymentmethods
  resources :customers
  resources :products
  resources :productcategories
  resources :suppliers
  resources :library_s
  resources :booklists
  resources :types
  resources :authors
  resources :borrows

  get 'sessions/new' 
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: [:new, :create]
  get 'sign_up', to: 'devise/registrations#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  resources :payments, only: [:new, :create]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'mingg#home'
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/booklist.rb
class Booklist < ApplicationRecord
  belongs_to :type
  validates_presence_of :tilte, :author, :publisher
  validates_uniqueness_of :tilte
 
  def self.search(term)
    if term.present?
      where('tilte LIKE ? OR author LIKE ? OR publisher LIKE ?', "%#{term}%", "%#{term}%", "%#{term}%")
    else
      all
    end
  end
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :booklist

  has_many :order
  validates_presence_of :name, :phone
  validates_numericality_of :phone
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :order
    validates_presence_of :name, :customerid, :phone, :email, :address
    validates_uniqueness_of :customerid
    validates_numericality_of :customerid, :phone
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  belongs_to :paymentmethod
  validates_presence_of :orderid, :customer, :product, :orderdate, :paymentmethod
  validates_uniqueness_of :orderid
  validates_numericality_of :orderid
end

app/models/payment.rb
# app/models/payment.rb
class Payment < ApplicationRecord
    # Các trường thông tin thanh toán, ví dụ: amount, card_number, expiration_date, cvv, etc.
  end
  

app/models/paymentmethod.rb
class Paymentmethod < ApplicationRecord
    has_many :order
    validates_presence_of :method
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier
  belongs_to :productcategory
  has_many :order
  validates_presence_of :name, :description, :price, :ingredient, :productcategory, :supplier, :quantity, :available
  validates_numericality_of :price, :quantity
  def self.search(term)
    if term
      where('name LIKE ?', "%#{term}%")
    else
      all
    end
    end
end

app/models/productcategory.rb
class Productcategory < ApplicationRecord
    has_many :products
    validates_presence_of :name
    
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :booklists
    validates_numericality_of :phone
    validates_presence_of :name, :address, :phone, :email
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :booklists
    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/userss.rb
class Userss < ApplicationRecord
    has_secure_password
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/library_s_helper.rb
module LibrarySHelper
end

app/helpers/mingg_helper.rb
module MinggHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/library_s/_form.html.erb
<%= form_with(model: library_) do |form| %>
<% if library_.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(library_.errors.count, "error") %> prohibited this library_ from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% library_.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= form.submit class: button_class(theme: 'primary') %>

<% if library_.persisted? %>
<%= link_to "Cancel", library_, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", library_s_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/library_s/_library_.html.erb
<div id="<%= dom_id library_ %>">
</div>

app/views/library_s/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit library_</h1>
    <% if @library_.persisted? %>
    <%= button_to 'Destroy', @library_, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', library_: @library_ %>
</div>

app/views/library_s/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Library_s</h1>

    <%= link_to new_library__path, class: button_class(theme: "primary") do %>
    Add New Library 
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
                
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
        
      </tr>
    </thead>

    <tbody>
      <% @library_s.each do |library_| %>
      <%= content_tag :tr, id: dom_id(library_), class: dom_class(library_) do %>
      

      
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to 'Show', library_ %></td>
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/library_s/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New library_</h1>

  <%= render 'form', library_: @library_ %>
</div>

app/views/library_s/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Library_</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to library_s_path, class: button_class(theme: "transparent") do %>
      All Library_s
      <% end %>
      <%= link_to edit_library__path(@library_), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
  </ul>
</div>