config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'authors/index'
  get 'authors/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/edit'
  get 'authors/update'
  get 'authors/destroy'
  resources :orders
  # resources :paymentmethods
  resources :customers
  resources :products
  resources :productcategories
  resources :suppliers
  resources :library_s
  resources :booklists
  resources :types
  resources :authors
  resources :borrows

  get 'sessions/new' 
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users, only: [:new, :create]
  get 'sign_up', to: 'devise/registrations#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  resources :payments, only: [:new, :create]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'mingg#home'
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/booklist.rb
class Booklist < ApplicationRecord
  belongs_to :type
  validates_presence_of :tilte, :author, :publisher
  validates_uniqueness_of :tilte
 
  def self.search(term)
    if term.present?
      where('tilte LIKE ? OR author LIKE ? OR publisher LIKE ?', "%#{term}%", "%#{term}%", "%#{term}%")
    else
      all
    end
  end
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :booklist

  has_many :order
  validates_presence_of :name, :phone
  validates_numericality_of :phone
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :order
    validates_presence_of :name, :customerid, :phone, :email, :address
    validates_uniqueness_of :customerid
    validates_numericality_of :customerid, :phone
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  belongs_to :paymentmethod
  validates_presence_of :orderid, :customer, :product, :orderdate, :paymentmethod
  validates_uniqueness_of :orderid
  validates_numericality_of :orderid
end

app/models/payment.rb
# app/models/payment.rb
class Payment < ApplicationRecord
    # Các trường thông tin thanh toán, ví dụ: amount, card_number, expiration_date, cvv, etc.
  end
  

app/models/paymentmethod.rb
class Paymentmethod < ApplicationRecord
    has_many :order
    validates_presence_of :method
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier
  belongs_to :productcategory
  has_many :order
  validates_presence_of :name, :description, :price, :ingredient, :productcategory, :supplier, :quantity, :available
  validates_numericality_of :price, :quantity
  def self.search(term)
    if term
      where('name LIKE ?', "%#{term}%")
    else
      all
    end
    end
end

app/models/productcategory.rb
class Productcategory < ApplicationRecord
    has_many :products
    validates_presence_of :name
    
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :booklists
    validates_numericality_of :phone
    validates_presence_of :name, :address, :phone, :email
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :booklists
    validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/userss.rb
class Userss < ApplicationRecord
    has_secure_password
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :set_borrow, only: %i[ show edit update destroy ]

  # GET /borrows or /borrows.json
  def index
    @borrows = Borrow.all
  end

  # GET /borrows/1 or /borrows/1.json
  def show
  end

  # GET /borrows/new
  def new
    @borrow = Borrow.new
  end

  # GET /borrows/1/edit
  def edit
  end

  # POST /borrows or /borrows.json
  def create
    @borrow = Borrow.new(borrow_params)

    respond_to do |format|
      if @borrow.save
        format.html { redirect_to borrow_url(@borrow), notice: "Borrow was successfully created." }
        format.json { render :show, status: :created, location: @borrow }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrows/1 or /borrows/1.json
  def update
    respond_to do |format|
      if @borrow.update(borrow_params)
        format.html { redirect_to borrow_url(@borrow), notice: "Borrow was successfully updated." }
        format.json { render :show, status: :ok, location: @borrow }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrows/1 or /borrows/1.json
  def destroy
    @borrow.destroy

    respond_to do |format|
      format.html { redirect_to borrows_url, notice: "Borrow was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def book_details
    @book = Booklist.find(params[:booklist_id])
    respond_to do |format|
      format.json { render json: @book }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrow
      @borrow = Borrow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def borrow_params
      params.require(:borrow).permit(:name, :studentid, :born, :phone, :booklist_id, :borrow_at, :return_at)
    end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/mingg_helper.rb
module MinggHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/borrows/_borrow.html.erb
<div id="<%= dom_id borrow %>">
  <p>
    <strong>Name:</strong>
    <%= borrow.name %>
  </p>

  <p>
    <strong>Studentid:</strong>
    <%= borrow.studentid %>
  </p>

  <p>
    <strong>Born:</strong>
    <%= borrow.born %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= borrow.phone %>
  </p>

  <p>
    <strong>Booklist:</strong>
    <%= borrow.booklist_id %>
  </p>

  <p>
    <strong>Borrow at:</strong>
    <%= borrow.borrow_at %>
  </p>

  <p>
    <strong>Return at:</strong>
    <%= borrow.return_at %>
  </p>

</div>

app/views/borrows/_form.html.erb
<script src="/assets/javascripts/borrows.js"></script>
<%= form_with(model: borrow, local: true) do |form| %>
  <% if borrow.errors.any? %>
  <div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
    <h2 class="text-lg font-semibold mb-3"><%= pluralize(borrow.errors.count, "error") %> prohibited this borrow from being saved:</h2>

    <ul class="list-disc leading-relaxed">
      <% borrow.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :name, class: label_class %>
    <%= form.text_field :name, class: input_class %>
  </div>
  <div class="mb-6">
    <%= form.label :userid, class: label_class %>
    <%= form.number_field :studentid, class: input_class %>
  </div>
  <div class="mb-6">
    <%= form.label :born, class: label_class %>
    <%= form.date_field :born, class: input_class %>
  </div>
  <div class="mb-6">
    <%= form.label :phone, class: label_class %>
    <%= form.number_field :phone, class: input_class %>
  </div>
  <div class="mb-6">
    <%= form.label :booklist_id, class: label_class %>
    <%= form.select :booklist_id, options_from_collection_for_select(Booklist.all, 'id', 'tilte', selected: borrow.booklist_id), id: 'booklist_select', class: input_class %>
  </div>
  <div id="book-details" class="mb-6">
    <!-- Additional book details will be displayed here -->
  </div>
  <div class="mb-6">
    <%= form.label :borrow_at, class: label_class %>
    <%= form.date_field :borrow_at, class: input_class %>
  </div>
  <div class="mb-6">
    <%= form.label :return_at, class: label_class %>
    <%= form.date_field :return_at, class: input_class %>
  </div>
  <%= form.submit class: button_class(theme: 'primary') %>
  <% if borrow.persisted? %>
    <%= link_to "Cancel", borrow, class: "text-neutral-700 underline inline-block ml-3" %>
  <% else %>
    <%= link_to "Cancel", borrows_path, class:  "text-neutral-700 underline inline-block ml-3" %>
  <% end %>
<% end %>

app/views/borrows/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit borrow</h1>
    <% if @borrow.persisted? %>
    <%= button_to 'Destroy', @borrow, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', borrow: @borrow %>
</div>

app/views/borrows/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Borrows</h1>

    <%= link_to new_borrow_path, class: button_class(theme: "primary") do %>
    Add New Borrow
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full" style="background-color: #C3F0E9">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Userid</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Born</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Phone</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Booklist</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Borrow at</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Return at</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left"></th>
                
      </tr>
    </thead>

    <tbody>
      <% @borrows.each do |borrow| %>
      <%= content_tag :tr, id: dom_id(borrow), class: dom_class(borrow) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to borrow.name, borrow %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-1200"><%= borrow.studentid %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-1200"><%= borrow.born %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-1200"><%= borrow.phone %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-1200"><%= borrow.booklist.tilte %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-1200"><%= borrow.borrow_at %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-1200"><%= borrow.return_at %></td>
            
            <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-1200"><%= link_to 'Show', borrow %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/borrows/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New borrow</h1>

  <%= render 'form', borrow: @borrow %>
</div>

app/views/borrows/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Borrow</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to borrows_path, class: button_class(theme: "transparent") do %>
      All Borrows
      <% end %>
      <%= link_to edit_borrow_path(@borrow), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @borrow.name %></p>
      </li>
      <li>
        <p class="font-semibold">Studentid:</p>
        <p><%= @borrow.studentid %></p>
      </li>
      <li>
        <p class="font-semibold">Born:</p>
        <p><%= @borrow.born %></p>
      </li>
      <li>
        <p class="font-semibold">Phone:</p>
        <p><%= @borrow.phone %></p>
      </li>
      <li>
        <p class="font-semibold">Booklist:</p>
        <p><%= @borrow.booklist.tilte %></p>
      </li>
      <li>
        <p class="font-semibold">Borrow at:</p>
        <p><%= @borrow.borrow_at %></p>
      </li>
      <li>
        <p class="font-semibold">Return at:</p>
        <p><%= @borrow.return_at %></p>
      </li>
  </ul>
</div>